### ISSUE TITLE
Sapper support

### ISSUE THREAD

**Issue by obrienmd** [mistlog/svelte-draft-tutorial#1]
Awesome project! Seems to work super well in my limited experimentation. I plan to give Sapper a go with svelte-draft soon, but am not sure how it would support something like preload, which lives in the module context of a Svelte component, and is not a part of a component's instance - [Sapper Preloading Docs](https://sapper.svelte.dev/docs#Preloading).

I suspect this is primarily due to my lack of experience with typedraft :) Would love feedback, and regardless, I plan to take a hack at this soson.

**Comment by mistlog** [comment]
> which lives in the module context of a Svelte component

Thanks!

Currently module context is not supported and I'm not familiar with sapper. Would you like to give some suggestions on the preferred way to support module context?

Take this piece of code in [svelte tutorial](https://svelte.dev/tutorial/module-exports) as an example:

```html
<script context="module">
	const elements = new Set();

	export function stopAll() {
		elements.forEach(element => {
			element.pause();
		});
	}
</script>

<script>
	import { onMount } from 'svelte';

	export let src;
	export let title;
	export let composer;
	export let performer;

	let audio;
	let paused = true;

	onMount(() => {
		elements.add(audio);
		return () => elements.delete(audio);
	});

	function stopOthers() {
		elements.forEach(element => {
			if (element !== audio) element.pause();
		});
	}
</script>

<article class:playing={!paused}>
	<h2>{title}</h2>
	<p><strong>{composer}</strong> / performed by {performer}</p>

	<audio
		bind:this={audio}
		bind:paused
		on:play={stopOthers}
		controls
		{src}
	></audio>
</article>
```

The .tsx counterpart would be something like, for example:

```javascript

// convention: anything outside a component is in module context
const elements = new Set();

export function stopAll() {
	elements.forEach(element => {
		element.pause();
	});
}

export default function AudioPlayer()
{
    ... omitted, any code related to component itself
}
```

But I'm not sure if it's preferred or intuitive.

**Comment by mistlog** [comment]
```shell
npm run transcribe
```
This command would generate all .svelte files from .tsx. Hope this is helpful if you want to inspect the translated final result.

**Comment by obrienmd** [comment]
Thanks for the quick reply. The example you refer to intuitively makes sense - I'll play around with transcription of sapper files soonish and let you know what I find!

**Comment by obrienmd** [comment]
After 30 minutes of playing around, it looks like Sapper's magic is going to make this non-trivial. Will try to dig in deeper next week and report back here!

**Comment by mistlog** [comment]
Thanks for spending time on it!
So I will try to implement module context based on the example and sync my progress here.

**Comment by obrienmd** [comment]
Of course - I'm on vacation somewhere warm, so I'm not giving it all it deserves, but I certainly will in the next week or so :)

I think the module context example you provided makes perfect sense, and I suspect it will work well both in Svelte proper and Sapper. I think, but am not sure, that Sapper's build magic will likely be a bigger hurdle. I made a bit of progress playing with it earlier, and I don't by any means think it will be insurmountable.

Thanks for the time you've put into this - it's a unique approach to the yet unsolved issue of typing Svelte across components :)

**Comment by mistlog** [comment]
Thanks for the hint, I will also inspect sapper.
Have a nice vacation!

**Comment by mistlog** [comment]
I implemented module context and examples are here: [17-module-context](https://github.com/mistlog/svelte-draft-tutorial/tree/master/src/examples/17-module-context).

**Comment by obrienmd** [comment]
Thanks much - it looks like it causes other components in the demo to fail right now. For example:

```
svelte-draft-tutorial master * = $ npm run dev

> svelte-app@1.0.0 dev C:\Users\micha\Documents\code\svelte-draft-tutorial
> rollup -c -w

rollup v1.31.0
bundles src/main.js → public\build\bundle.js...
[!] (plugin at position 1) TypeError: Cannot read property 'get' of undefined
src\examples\10-transitions\custom-css-transitions\App.svelte.tsx
TypeError: Cannot read property 'get' of undefined
    at SvelteTranscriber.ExtractModuleContext (C:\blahblah\svelte-draft-tutorial\node_modules\svelte-draft\dist\src\transcriber\svelte-transcriber.js:21:40)
    at Transcribe (C:\blahblah\svelte-draft-tutorial\node_modules\svelte-draft\dist\cli\literator.js:147:40)
    at Object.<anonymous> (C:\blahblah\svelte-draft-tutorial\node_modules\svelte-draft\dist\cli\literator.js:122:86)
    at Generator.next (<anonymous>)
    at fulfilled (C:\blahblah\svelte-draft-tutorial\node_modules\svelte-draft\dist\cli\literator.js:5:58)
````

**Comment by mistlog** [comment]
I tried again and it works well, so would you like to test this zip so that the environment of us is the same and we can find the difference: [svelte-draft-tutorial-master.zip](https://github.com/mistlog/svelte-draft-tutorial/files/4242892/svelte-draft-tutorial-master.zip)

Or clean node_modules and reinstall because I find that the structure of node_modules in the error report is not the same: `\svelte-draft-tutorial\node_modules\svelte-draft`,  and the `svelte-draft` package should be in the directory `\node_modules\rollup-plugin-svelte-draft` after update.

**Comment by obrienmd** [comment]
Hrm, no folders diffs save for packages-lock.json (some different versions were selected for dependencies). Running "npm run dev" against that zipped folder also throws the same error.

I cleaned node_modules and reinstalled as well. In both that case, and with the zipped folder above after npm install, the svelte-draft module is not nested under rollup-plugin-svelte-draft.

Environment:
OS in Win10 x64
node version v12.16.1
npm version 6.13.4

**Comment by obrienmd** [comment]
Prior to the line that throws the error, "this" evaluates to (notice m_Path would be undefined):

```
SvelteTranscriber {
  m_Module: ModuleCode {
    m_File: Node {
      type: 'File',
      start: 0,
      end: 484,
      loc: [SourceLocation],
      errors: [],
      program: [Node],
      comments: []
    }
  },
  m_ClassMap: Map {},
  m_MethodMap: Map {},
  m_ContextMap: Map {},
  m_DSLMap: Map { 'watch' => SvelteWatch {} },
  m_Plugins: [
    DSLPlugin { m_Transcriber: [Circular] },
    ClassPlugin { m_Transcriber: [Circular] },
    LocalContextPlugin { m_Transcriber: [Circular] },
    SvelteFilterPlugin { m_Transcriber: [Circular] }
  ]
}
```

**Comment by mistlog** [comment]
oh! I find the problem, after switching to node  v12.16.1, it throws error.
So it works in node v10.1.0 and npm 5.6.0, and I will try to find a solution.

**Comment by mistlog** [comment]
I fixed it! Yesterday I updated typedraft but didn't realize that it's breaking change for svelte-draft.
I will pay more attention to semantic versioning later on. But I still don't know why it works in lower version of node, maybe the package resolution policy changed during npm 5.x -> 6.x.

Get latest code, reinstall and it works, I just updated rollup-plugin-svelte-draft version. I'm sorry that it wasted your time.

**Comment by mistlog** [comment]
As for sapper support, I'm working on refactoring rollup-plugin-svelte-draft so that it can be used in both svelte and sapper. The naming convention of files in sapper is really tricky.

**Comment by obrienmd** [comment]
Thank you! Fix works :)

Looking forward to testing sapper - it _is_ tricky :) On the other hand, it does quite a bit of fun magic for you. In the meantime, I've started playing with svelte-routing instead - resulted in an issue I dropped in svelte-draft repo, which is probably where this should have been :) I won't link it as it's not really related, I hope that's reasonable etiquette!

**Comment by mistlog** [comment]
You are welcome, thanks for finding these problems as well!

**Comment by mistlog** [comment]
It works! see https://github.com/mistlog/sapper-template for an example. :)
